// Generated from docs/route-registry.json by scripts/generate-mobile-routes.mjs.
// Do not edit: change the registry (SF-31) and run `pnpm routes:generate`.

export const mobileRoutes = [
  {
    id: "mobile.account.appeal",
    path: "/account/appeal",
    params: [],
    shell: "mobile.shared",
    surface: "SHARED",
    parent: null,
    nav: "STANDALONE",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: null,
    phase: null,
    restrictedAccount: true,
  },
  {
    id: "mobile.account.pending-deletion",
    path: "/account/pending-deletion",
    params: [],
    shell: "mobile.shared",
    surface: "SHARED",
    parent: null,
    nav: "STANDALONE",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: null,
    phase: null,
    restrictedAccount: true,
  },
  {
    id: "mobile.account.suspended",
    path: "/account/suspended",
    params: [],
    shell: "mobile.shared",
    surface: "SHARED",
    parent: null,
    nav: "STANDALONE",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: null,
    phase: null,
    restrictedAccount: true,
  },
  {
    id: "mobile.achievements",
    path: "/achievements",
    params: [],
    shell: "mobile.fighter",
    surface: "FIGHTER",
    parent: null,
    nav: "STANDALONE",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: "FIGHTER",
    phase: "ACTIVE",
    restrictedAccount: false,
  },
  {
    id: "mobile.achievements._achievement-id",
    path: "/achievements/:achievementId",
    params: ["achievementId"],
    shell: "mobile.fighter",
    surface: "FIGHTER",
    parent: "mobile.achievements",
    nav: "STACK",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: "FIGHTER",
    phase: "ACTIVE",
    restrictedAccount: false,
  },
  {
    id: "mobile.activity._activity-id",
    path: "/activity/:activityId",
    params: ["activityId"],
    shell: "mobile.fighter",
    surface: "FIGHTER",
    parent: null,
    nav: "STANDALONE",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: "FIGHTER",
    phase: "ACTIVE",
    restrictedAccount: false,
  },
  {
    id: "mobile.app",
    path: "/app",
    params: [],
    shell: "mobile.root",
    surface: "INTERNAL",
    parent: null,
    nav: "STANDALONE",
    status: "IMPLEMENTED",
    session: "PUBLIC",
    capability: null,
    phase: null,
    restrictedAccount: false,
  },
  {
    id: "mobile.billing.cancel",
    path: "/billing/cancel",
    params: [],
    shell: "mobile.shared",
    surface: "SHARED",
    parent: null,
    nav: "STANDALONE",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: null,
    phase: null,
    restrictedAccount: false,
  },
  {
    id: "mobile.billing.info",
    path: "/billing/info",
    params: [],
    shell: "mobile.shared",
    surface: "SHARED",
    parent: null,
    nav: "STANDALONE",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: null,
    phase: null,
    restrictedAccount: false,
  },
  {
    id: "mobile.billing.methods",
    path: "/billing/methods",
    params: [],
    shell: "mobile.shared",
    surface: "SHARED",
    parent: null,
    nav: "STANDALONE",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: null,
    phase: null,
    restrictedAccount: false,
  },
  {
    id: "mobile.billing.methods.new",
    path: "/billing/methods/new",
    params: [],
    shell: "mobile.shared",
    surface: "SHARED",
    parent: "mobile.billing.methods",
    nav: "STACK",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: null,
    phase: null,
    restrictedAccount: false,
  },
  {
    id: "mobile.billing.upgrade",
    path: "/billing/upgrade",
    params: [],
    shell: "mobile.shared",
    surface: "SHARED",
    parent: null,
    nav: "STANDALONE",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: null,
    phase: null,
    restrictedAccount: false,
  },
  {
    id: "mobile.board",
    path: "/board",
    params: [],
    shell: "mobile.fighter",
    surface: "FIGHTER",
    parent: null,
    nav: "NAV_ITEM",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: "FIGHTER",
    phase: "ACTIVE",
    restrictedAccount: false,
  },
  {
    id: "mobile.board.node.fighter._fighter-id",
    path: "/board/node/fighter/:fighterId",
    params: ["fighterId"],
    shell: "mobile.fighter",
    surface: "FIGHTER",
    parent: "mobile.board",
    nav: "STACK",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: "FIGHTER",
    phase: "ACTIVE",
    restrictedAccount: false,
  },
  {
    id: "mobile.board.node.gym._gym-id",
    path: "/board/node/gym/:gymId",
    params: ["gymId"],
    shell: "mobile.fighter",
    surface: "FIGHTER",
    parent: "mobile.board",
    nav: "STACK",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: "FIGHTER",
    phase: "ACTIVE",
    restrictedAccount: false,
  },
  {
    id: "mobile.board.node.training._training-id",
    path: "/board/node/training/:trainingId",
    params: ["trainingId"],
    shell: "mobile.fighter",
    surface: "FIGHTER",
    parent: "mobile.board",
    nav: "STACK",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: "FIGHTER",
    phase: "ACTIVE",
    restrictedAccount: false,
  },
  {
    id: "mobile.book.pt",
    path: "/book/pt",
    params: [],
    shell: "mobile.fighter",
    surface: "FIGHTER",
    parent: null,
    nav: "STANDALONE",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: "FIGHTER",
    phase: "ACTIVE",
    restrictedAccount: false,
  },
  {
    id: "mobile.calendar",
    path: "/calendar",
    params: [],
    shell: "mobile.fighter",
    surface: "FIGHTER",
    parent: null,
    nav: "STANDALONE",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: "FIGHTER",
    phase: "ACTIVE",
    restrictedAccount: false,
  },
  {
    id: "mobile.camp",
    path: "/camp",
    params: [],
    shell: "mobile.fighter",
    surface: "FIGHTER",
    parent: null,
    nav: "STANDALONE",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: "FIGHTER",
    phase: "ACTIVE",
    restrictedAccount: false,
  },
  {
    id: "mobile.camp.weight",
    path: "/camp/weight",
    params: [],
    shell: "mobile.fighter",
    surface: "FIGHTER",
    parent: "mobile.camp",
    nav: "STACK",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: "FIGHTER",
    phase: "ACTIVE",
    restrictedAccount: false,
  },
  {
    id: "mobile.challenges",
    path: "/challenges",
    params: [],
    shell: "mobile.fighter",
    surface: "FIGHTER",
    parent: null,
    nav: "STANDALONE",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: "FIGHTER",
    phase: "ACTIVE",
    restrictedAccount: false,
  },
  {
    id: "mobile.challenges._challenge-id",
    path: "/challenges/:challengeId",
    params: ["challengeId"],
    shell: "mobile.fighter",
    surface: "FIGHTER",
    parent: "mobile.challenges",
    nav: "STACK",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: "FIGHTER",
    phase: "ACTIVE",
    restrictedAccount: false,
  },
  {
    id: "mobile.checkout",
    path: "/checkout",
    params: [],
    shell: "mobile.shared",
    surface: "SHARED",
    parent: null,
    nav: "STANDALONE",
    status: "IMPLEMENTED",
    session: "PUBLIC",
    capability: null,
    phase: null,
    restrictedAccount: false,
  },
  {
    id: "mobile.coach._coach-id.services._service-id",
    path: "/coach/:coachId/services/:serviceId",
    params: ["coachId", "serviceId"],
    shell: "mobile.fighter",
    surface: "FIGHTER",
    parent: null,
    nav: "STANDALONE",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: "FIGHTER",
    phase: "ACTIVE",
    restrictedAccount: false,
  },
  {
    id: "mobile.coach.activity",
    path: "/coach/activity",
    params: [],
    shell: "mobile.coach",
    surface: "COACH",
    parent: null,
    nav: "STANDALONE",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: "COACH",
    phase: "ACTIVE",
    restrictedAccount: false,
  },
  {
    id: "mobile.coach.ai-drafts",
    path: "/coach/ai-drafts",
    params: [],
    shell: "mobile.coach",
    surface: "COACH",
    parent: null,
    nav: "STANDALONE",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: "COACH",
    phase: "ACTIVE",
    restrictedAccount: false,
  },
  {
    id: "mobile.coach.board",
    path: "/coach/board",
    params: [],
    shell: "mobile.coach",
    surface: "COACH",
    parent: null,
    nav: "NAV_ITEM",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: "COACH",
    phase: "ACTIVE",
    restrictedAccount: false,
  },
  {
    id: "mobile.coach.challenge._challenge-id",
    path: "/coach/challenge/:challengeId",
    params: ["challengeId"],
    shell: "mobile.coach",
    surface: "COACH",
    parent: null,
    nav: "STANDALONE",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: "COACH",
    phase: "ACTIVE",
    restrictedAccount: false,
  },
  {
    id: "mobile.coach.earnings",
    path: "/coach/earnings",
    params: [],
    shell: "mobile.coach",
    surface: "COACH",
    parent: null,
    nav: "STANDALONE",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: "COACH",
    phase: "ACTIVE",
    restrictedAccount: false,
  },
  {
    id: "mobile.coach.fighters",
    path: "/coach/fighters",
    params: [],
    shell: "mobile.coach",
    surface: "COACH",
    parent: null,
    nav: "NAV_ITEM",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: "COACH",
    phase: "ACTIVE",
    restrictedAccount: false,
  },
  {
    id: "mobile.coach.fighters._fighter-id",
    path: "/coach/fighters/:fighterId",
    params: ["fighterId"],
    shell: "mobile.coach",
    surface: "COACH",
    parent: "mobile.coach.fighters",
    nav: "STACK",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: "COACH",
    phase: "ACTIVE",
    restrictedAccount: false,
  },
  {
    id: "mobile.coach.fighters._fighter-id.note",
    path: "/coach/fighters/:fighterId/note",
    params: ["fighterId"],
    shell: "mobile.coach",
    surface: "COACH",
    parent: "mobile.coach.fighters._fighter-id",
    nav: "STACK",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: "COACH",
    phase: "ACTIVE",
    restrictedAccount: false,
  },
  {
    id: "mobile.coach.promote",
    path: "/coach/promote",
    params: [],
    shell: "mobile.coach",
    surface: "COACH",
    parent: null,
    nav: "STANDALONE",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: "COACH",
    phase: "ACTIVE",
    restrictedAccount: false,
  },
  {
    id: "mobile.coach.promote.results",
    path: "/coach/promote/results",
    params: [],
    shell: "mobile.coach",
    surface: "COACH",
    parent: "mobile.coach.promote",
    nav: "STACK",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: "COACH",
    phase: "ACTIVE",
    restrictedAccount: false,
  },
  {
    id: "mobile.coach.requests",
    path: "/coach/requests",
    params: [],
    shell: "mobile.coach",
    surface: "COACH",
    parent: null,
    nav: "NAV_ITEM",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: "COACH",
    phase: "ACTIVE",
    restrictedAccount: false,
  },
  {
    id: "mobile.coach.services",
    path: "/coach/services",
    params: [],
    shell: "mobile.coach",
    surface: "COACH",
    parent: null,
    nav: "STANDALONE",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: "COACH",
    phase: "ACTIVE",
    restrictedAccount: false,
  },
  {
    id: "mobile.coach.sessions._session-id.live",
    path: "/coach/sessions/:sessionId/live",
    params: ["sessionId"],
    shell: "mobile.coach",
    surface: "COACH",
    parent: null,
    nav: "STANDALONE",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: "COACH",
    phase: "ACTIVE",
    restrictedAccount: false,
  },
  {
    id: "mobile.coach.sessions._session-id.roster",
    path: "/coach/sessions/:sessionId/roster",
    params: ["sessionId"],
    shell: "mobile.coach",
    surface: "COACH",
    parent: null,
    nav: "STANDALONE",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: "COACH",
    phase: "ACTIVE",
    restrictedAccount: false,
  },
  {
    id: "mobile.coach.shared._shared-session-id",
    path: "/coach/shared/:sharedSessionId",
    params: ["sharedSessionId"],
    shell: "mobile.coach",
    surface: "COACH",
    parent: null,
    nav: "STANDALONE",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: "COACH",
    phase: "ACTIVE",
    restrictedAccount: false,
  },
  {
    id: "mobile.coach.sparring",
    path: "/coach/sparring",
    params: [],
    shell: "mobile.coach",
    surface: "COACH",
    parent: null,
    nav: "STANDALONE",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: "COACH",
    phase: "ACTIVE",
    restrictedAccount: false,
  },
  {
    id: "mobile.coach.sparring._sparring-id.live",
    path: "/coach/sparring/:sparringId/live",
    params: ["sparringId"],
    shell: "mobile.coach",
    surface: "COACH",
    parent: "mobile.coach.sparring",
    nav: "STACK",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: "COACH",
    phase: "ACTIVE",
    restrictedAccount: false,
  },
  {
    id: "mobile.coach.sparring._sparring-id.video",
    path: "/coach/sparring/:sparringId/video",
    params: ["sparringId"],
    shell: "mobile.coach",
    surface: "COACH",
    parent: "mobile.coach.sparring",
    nav: "STACK",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: "COACH",
    phase: "ACTIVE",
    restrictedAccount: false,
  },
  {
    id: "mobile.coach.today",
    path: "/coach/today",
    params: [],
    shell: "mobile.coach",
    surface: "COACH",
    parent: null,
    nav: "NAV_ITEM",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: "COACH",
    phase: "ACTIVE",
    restrictedAccount: false,
  },
  {
    id: "mobile.coach.welcome",
    path: "/coach/welcome",
    params: [],
    shell: "mobile.onboarding",
    surface: "ONBOARDING",
    parent: null,
    nav: "WIZARD",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: "COACH",
    phase: "ACTIVE",
    restrictedAccount: false,
  },
  {
    id: "mobile.community",
    path: "/community",
    params: [],
    shell: "mobile.fighter",
    surface: "FIGHTER",
    parent: null,
    nav: "NAV_ITEM",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: "FIGHTER",
    phase: "ACTIVE",
    restrictedAccount: false,
  },
  {
    id: "mobile.dev.design-system",
    path: "/dev/design-system",
    params: [],
    shell: "mobile.root",
    surface: "INTERNAL",
    parent: null,
    nav: "STANDALONE",
    status: "IMPLEMENTED",
    session: "PUBLIC",
    capability: null,
    phase: null,
    restrictedAccount: false,
  },
  {
    id: "mobile.discover",
    path: "/discover",
    params: [],
    shell: "mobile.fighter",
    surface: "FIGHTER",
    parent: null,
    nav: "STANDALONE",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: "FIGHTER",
    phase: "ACTIVE",
    restrictedAccount: false,
  },
  {
    id: "mobile.events._event-id",
    path: "/events/:eventId",
    params: ["eventId"],
    shell: "mobile.fighter",
    surface: "FIGHTER",
    parent: null,
    nav: "STANDALONE",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: "FIGHTER",
    phase: "ACTIVE",
    restrictedAccount: false,
  },
  {
    id: "mobile.events._event-id.register",
    path: "/events/:eventId/register",
    params: ["eventId"],
    shell: "mobile.fighter",
    surface: "FIGHTER",
    parent: "mobile.events._event-id",
    nav: "STACK",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: "FIGHTER",
    phase: "ACTIVE",
    restrictedAccount: false,
  },
  {
    id: "mobile.following",
    path: "/following",
    params: [],
    shell: "mobile.fighter",
    surface: "FIGHTER",
    parent: null,
    nav: "STANDALONE",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: "FIGHTER",
    phase: "ACTIVE",
    restrictedAccount: false,
  },
  {
    id: "mobile.friends",
    path: "/friends",
    params: [],
    shell: "mobile.fighter",
    surface: "FIGHTER",
    parent: null,
    nav: "STANDALONE",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: "FIGHTER",
    phase: "ACTIVE",
    restrictedAccount: false,
  },
  {
    id: "mobile.gym._gym-id.classes._class-id.book",
    path: "/gym/:gymId/classes/:classId/book",
    params: ["gymId", "classId"],
    shell: "mobile.fighter",
    surface: "FIGHTER",
    parent: null,
    nav: "STANDALONE",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: "FIGHTER",
    phase: "ACTIVE",
    restrictedAccount: false,
  },
  {
    id: "mobile.gym._gym-id.community",
    path: "/gym/:gymId/community",
    params: ["gymId"],
    shell: "mobile.fighter",
    surface: "FIGHTER",
    parent: null,
    nav: "STANDALONE",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: "FIGHTER",
    phase: "ACTIVE",
    restrictedAccount: false,
  },
  {
    id: "mobile.gym._gym-id.memberships",
    path: "/gym/:gymId/memberships",
    params: ["gymId"],
    shell: "mobile.fighter",
    surface: "FIGHTER",
    parent: null,
    nav: "STANDALONE",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: "FIGHTER",
    phase: "ACTIVE",
    restrictedAccount: false,
  },
  {
    id: "mobile.gym._gym-id.memberships._membership-id",
    path: "/gym/:gymId/memberships/:membershipId",
    params: ["gymId", "membershipId"],
    shell: "mobile.fighter",
    surface: "FIGHTER",
    parent: "mobile.gym._gym-id.memberships",
    nav: "STACK",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: "FIGHTER",
    phase: "ACTIVE",
    restrictedAccount: false,
  },
  {
    id: "mobile.gym._gym-id.store",
    path: "/gym/:gymId/store",
    params: ["gymId"],
    shell: "mobile.fighter",
    surface: "FIGHTER",
    parent: null,
    nav: "STANDALONE",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: "FIGHTER",
    phase: "ACTIVE",
    restrictedAccount: false,
  },
  {
    id: "mobile.gym.announcements.new",
    path: "/gym/announcements/new",
    params: [],
    shell: "mobile.gym",
    surface: "GYM",
    parent: null,
    nav: "STANDALONE",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: "GYM_WORKSPACE",
    phase: "ACTIVE",
    restrictedAccount: false,
  },
  {
    id: "mobile.gym.check-in",
    path: "/gym/check-in",
    params: [],
    shell: "mobile.gym",
    surface: "GYM",
    parent: null,
    nav: "NAV_ITEM",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: "GYM_WORKSPACE",
    phase: "ACTIVE",
    restrictedAccount: false,
  },
  {
    id: "mobile.gym.classes",
    path: "/gym/classes",
    params: [],
    shell: "mobile.gym",
    surface: "GYM",
    parent: null,
    nav: "NAV_ITEM",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: "GYM_WORKSPACE",
    phase: "ACTIVE",
    restrictedAccount: false,
  },
  {
    id: "mobile.gym.classes._class-id.roster",
    path: "/gym/classes/:classId/roster",
    params: ["classId"],
    shell: "mobile.gym",
    surface: "GYM",
    parent: "mobile.gym.classes",
    nav: "STACK",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: "GYM_WORKSPACE",
    phase: "ACTIVE",
    restrictedAccount: false,
  },
  {
    id: "mobile.gym.incidents.new",
    path: "/gym/incidents/new",
    params: [],
    shell: "mobile.gym",
    surface: "GYM",
    parent: null,
    nav: "STANDALONE",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: "GYM_WORKSPACE",
    phase: "ACTIVE",
    restrictedAccount: false,
  },
  {
    id: "mobile.gym.members",
    path: "/gym/members",
    params: [],
    shell: "mobile.gym",
    surface: "GYM",
    parent: null,
    nav: "NAV_ITEM",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: "GYM_WORKSPACE",
    phase: "ACTIVE",
    restrictedAccount: false,
  },
  {
    id: "mobile.gym.members._member-id",
    path: "/gym/members/:memberId",
    params: ["memberId"],
    shell: "mobile.gym",
    surface: "GYM",
    parent: "mobile.gym.members",
    nav: "STACK",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: "GYM_WORKSPACE",
    phase: "ACTIVE",
    restrictedAccount: false,
  },
  {
    id: "mobile.gym.pulse",
    path: "/gym/pulse",
    params: [],
    shell: "mobile.gym",
    surface: "GYM",
    parent: null,
    nav: "NAV_ITEM",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: "GYM_WORKSPACE",
    phase: "ACTIVE",
    restrictedAccount: false,
  },
  {
    id: "mobile.gym.staff.on-shift",
    path: "/gym/staff/on-shift",
    params: [],
    shell: "mobile.gym",
    surface: "GYM",
    parent: null,
    nav: "NAV_ITEM",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: "GYM_WORKSPACE",
    phase: "ACTIVE",
    restrictedAccount: false,
  },
  {
    id: "mobile.home",
    path: "/home",
    params: [],
    shell: "mobile.fighter",
    surface: "FIGHTER",
    parent: null,
    nav: "NAV_ITEM",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: "FIGHTER",
    phase: "ACTIVE",
    restrictedAccount: false,
  },
  {
    id: "mobile.invite._code",
    path: "/invite/:code",
    params: ["code"],
    shell: "mobile.auth",
    surface: "AUTH",
    parent: null,
    nav: "STANDALONE",
    status: "IMPLEMENTED",
    session: "PUBLIC",
    capability: null,
    phase: null,
    restrictedAccount: false,
  },
  {
    id: "mobile.invite.coach._token",
    path: "/invite/coach/:token",
    params: ["token"],
    shell: "mobile.auth",
    surface: "AUTH",
    parent: null,
    nav: "STANDALONE",
    status: "IMPLEMENTED",
    session: "PUBLIC",
    capability: null,
    phase: null,
    restrictedAccount: false,
  },
  {
    id: "mobile.invite.friend",
    path: "/invite/friend",
    params: [],
    shell: "mobile.auth",
    surface: "AUTH",
    parent: null,
    nav: "STANDALONE",
    status: "IMPLEMENTED",
    session: "PUBLIC",
    capability: null,
    phase: null,
    restrictedAccount: false,
  },
  {
    id: "mobile.invite.staff._token",
    path: "/invite/staff/:token",
    params: ["token"],
    shell: "mobile.auth",
    surface: "AUTH",
    parent: null,
    nav: "STANDALONE",
    status: "IMPLEMENTED",
    session: "PUBLIC",
    capability: null,
    phase: null,
    restrictedAccount: false,
  },
  {
    id: "mobile.invite.staff._token.confirm",
    path: "/invite/staff/:token/confirm",
    params: ["token"],
    shell: "mobile.auth",
    surface: "AUTH",
    parent: "mobile.invite.staff._token",
    nav: "STACK",
    status: "IMPLEMENTED",
    session: "PUBLIC",
    capability: null,
    phase: null,
    restrictedAccount: false,
  },
  {
    id: "mobile.join._code",
    path: "/join/:code",
    params: ["code"],
    shell: "mobile.auth",
    surface: "AUTH",
    parent: null,
    nav: "STANDALONE",
    status: "IMPLEMENTED",
    session: "PUBLIC",
    capability: null,
    phase: null,
    restrictedAccount: false,
  },
  {
    id: "mobile.login",
    path: "/login",
    params: [],
    shell: "mobile.auth",
    surface: "AUTH",
    parent: null,
    nav: "STANDALONE",
    status: "IMPLEMENTED",
    session: "GUEST_ONLY",
    capability: null,
    phase: null,
    restrictedAccount: false,
  },
  {
    id: "mobile.login.code",
    path: "/login/code",
    params: [],
    shell: "mobile.auth",
    surface: "AUTH",
    parent: "mobile.login",
    nav: "STANDALONE",
    status: "IMPLEMENTED",
    session: "GUEST_ONLY",
    capability: null,
    phase: null,
    restrictedAccount: false,
  },
  {
    id: "mobile.marketplace",
    path: "/marketplace",
    params: [],
    shell: "mobile.fighter",
    surface: "FIGHTER",
    parent: null,
    nav: "STANDALONE",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: "FIGHTER",
    phase: "ACTIVE",
    restrictedAccount: false,
  },
  {
    id: "mobile.marketplace.coach._coach-id",
    path: "/marketplace/coach/:coachId",
    params: ["coachId"],
    shell: "mobile.fighter",
    surface: "FIGHTER",
    parent: "mobile.marketplace",
    nav: "STACK",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: "FIGHTER",
    phase: "ACTIVE",
    restrictedAccount: false,
  },
  {
    id: "mobile.marketplace.gym._gym-id",
    path: "/marketplace/gym/:gymId",
    params: ["gymId"],
    shell: "mobile.fighter",
    surface: "FIGHTER",
    parent: "mobile.marketplace",
    nav: "STACK",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: "FIGHTER",
    phase: "ACTIVE",
    restrictedAccount: false,
  },
  {
    id: "mobile.marketplace.program._program-id",
    path: "/marketplace/program/:programId",
    params: ["programId"],
    shell: "mobile.fighter",
    surface: "FIGHTER",
    parent: "mobile.marketplace",
    nav: "STACK",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: "FIGHTER",
    phase: "ACTIVE",
    restrictedAccount: false,
  },
  {
    id: "mobile.me.credits",
    path: "/me/credits",
    params: [],
    shell: "mobile.fighter",
    surface: "FIGHTER",
    parent: null,
    nav: "STANDALONE",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: "FIGHTER",
    phase: "ACTIVE",
    restrictedAccount: false,
  },
  {
    id: "mobile.me.membership",
    path: "/me/membership",
    params: [],
    shell: "mobile.fighter",
    surface: "FIGHTER",
    parent: null,
    nav: "STANDALONE",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: "FIGHTER",
    phase: "ACTIVE",
    restrictedAccount: false,
  },
  {
    id: "mobile.me.programs._program-id",
    path: "/me/programs/:programId",
    params: ["programId"],
    shell: "mobile.fighter",
    surface: "FIGHTER",
    parent: null,
    nav: "STANDALONE",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: "FIGHTER",
    phase: "ACTIVE",
    restrictedAccount: false,
  },
  {
    id: "mobile.membership",
    path: "/membership",
    params: [],
    shell: "mobile.fighter",
    surface: "FIGHTER",
    parent: null,
    nav: "STANDALONE",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: "FIGHTER",
    phase: "ACTIVE",
    restrictedAccount: false,
  },
  {
    id: "mobile.messages",
    path: "/messages",
    params: [],
    shell: "mobile.shared",
    surface: "SHARED",
    parent: null,
    nav: "NAV_ITEM",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: null,
    phase: null,
    restrictedAccount: false,
  },
  {
    id: "mobile.messages._thread-id",
    path: "/messages/:threadId",
    params: ["threadId"],
    shell: "mobile.shared",
    surface: "SHARED",
    parent: "mobile.messages",
    nav: "STACK",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: null,
    phase: null,
    restrictedAccount: false,
  },
  {
    id: "mobile.not-found",
    path: "/*",
    params: [],
    shell: "mobile.root",
    surface: "SYSTEM",
    parent: null,
    nav: "CATCH_ALL",
    status: "IMPLEMENTED",
    session: "PUBLIC",
    capability: null,
    phase: null,
    restrictedAccount: false,
  },
  {
    id: "mobile.notifications",
    path: "/notifications",
    params: [],
    shell: "mobile.shared",
    surface: "SHARED",
    parent: null,
    nav: "STANDALONE",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: null,
    phase: null,
    restrictedAccount: false,
  },
  {
    id: "mobile.onboarding.coach",
    path: "/onboarding/coach",
    params: [],
    shell: "mobile.onboarding",
    surface: "ONBOARDING",
    parent: null,
    nav: "WIZARD",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: null,
    phase: "ONBOARDING",
    restrictedAccount: false,
  },
  {
    id: "mobile.onboarding.fighter",
    path: "/onboarding/fighter",
    params: [],
    shell: "mobile.onboarding",
    surface: "ONBOARDING",
    parent: null,
    nav: "WIZARD",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: null,
    phase: "ONBOARDING",
    restrictedAccount: false,
  },
  {
    id: "mobile.onboarding.gym",
    path: "/onboarding/gym",
    params: [],
    shell: "mobile.onboarding",
    surface: "ONBOARDING",
    parent: null,
    nav: "STANDALONE",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: null,
    phase: "ONBOARDING",
    restrictedAccount: false,
  },
  {
    id: "mobile.onboarding.role",
    path: "/onboarding/role",
    params: [],
    shell: "mobile.auth",
    surface: "AUTH",
    parent: null,
    nav: "STANDALONE",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: null,
    phase: "ONBOARDING",
    restrictedAccount: false,
  },
  {
    id: "mobile.onboarding.staff.location",
    path: "/onboarding/staff/location",
    params: [],
    shell: "mobile.onboarding",
    surface: "ONBOARDING",
    parent: null,
    nav: "STANDALONE",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: "GYM_WORKSPACE",
    phase: "ONBOARDING",
    restrictedAccount: false,
  },
  {
    id: "mobile.onboarding.staff.role",
    path: "/onboarding/staff/role",
    params: [],
    shell: "mobile.onboarding",
    surface: "ONBOARDING",
    parent: null,
    nav: "STANDALONE",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: "GYM_WORKSPACE",
    phase: "ONBOARDING",
    restrictedAccount: false,
  },
  {
    id: "mobile.onboarding.staff.tour",
    path: "/onboarding/staff/tour",
    params: [],
    shell: "mobile.onboarding",
    surface: "ONBOARDING",
    parent: null,
    nav: "STANDALONE",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: "GYM_WORKSPACE",
    phase: "ONBOARDING",
    restrictedAccount: false,
  },
  {
    id: "mobile.payments",
    path: "/payments",
    params: [],
    shell: "mobile.fighter",
    surface: "FIGHTER",
    parent: null,
    nav: "STANDALONE",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: "FIGHTER",
    phase: "ACTIVE",
    restrictedAccount: false,
  },
  {
    id: "mobile.pricing",
    path: "/pricing",
    params: [],
    shell: "mobile.shared",
    surface: "SHARED",
    parent: null,
    nav: "STANDALONE",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: null,
    phase: null,
    restrictedAccount: false,
  },
  {
    id: "mobile.pricing.compare",
    path: "/pricing/compare",
    params: [],
    shell: "mobile.shared",
    surface: "SHARED",
    parent: "mobile.pricing",
    nav: "STACK",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: null,
    phase: null,
    restrictedAccount: false,
  },
  {
    id: "mobile.pro",
    path: "/pro",
    params: [],
    shell: "mobile.fighter",
    surface: "FIGHTER",
    parent: null,
    nav: "STANDALONE",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: "FIGHTER",
    phase: "ACTIVE",
    restrictedAccount: false,
  },
  {
    id: "mobile.profile",
    path: "/profile",
    params: [],
    shell: "mobile.fighter",
    surface: "FIGHTER",
    parent: null,
    nav: "NAV_ITEM",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: "FIGHTER",
    phase: "ACTIVE",
    restrictedAccount: false,
  },
  {
    id: "mobile.profile.fighter._fighter-id",
    path: "/profile/fighter/:fighterId",
    params: ["fighterId"],
    shell: "mobile.fighter",
    surface: "FIGHTER",
    parent: "mobile.profile",
    nav: "STACK",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: "FIGHTER",
    phase: "ACTIVE",
    restrictedAccount: false,
  },
  {
    id: "mobile.progress",
    path: "/progress",
    params: [],
    shell: "mobile.fighter",
    surface: "FIGHTER",
    parent: null,
    nav: "STANDALONE",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: "FIGHTER",
    phase: "ACTIVE",
    restrictedAccount: false,
  },
  {
    id: "mobile.progress.sparring",
    path: "/progress/sparring",
    params: [],
    shell: "mobile.fighter",
    surface: "FIGHTER",
    parent: "mobile.progress",
    nav: "STACK",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: "FIGHTER",
    phase: "ACTIVE",
    restrictedAccount: false,
  },
  {
    id: "mobile.progress.video._video-id",
    path: "/progress/video/:videoId",
    params: ["videoId"],
    shell: "mobile.fighter",
    surface: "FIGHTER",
    parent: "mobile.progress",
    nav: "STACK",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: "FIGHTER",
    phase: "ACTIVE",
    restrictedAccount: false,
  },
  {
    id: "mobile.report",
    path: "/report",
    params: [],
    shell: "mobile.fighter",
    surface: "FIGHTER",
    parent: null,
    nav: "STANDALONE",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: "FIGHTER",
    phase: "ACTIVE",
    restrictedAccount: false,
  },
  {
    id: "mobile.root",
    path: "/",
    params: [],
    shell: "mobile.root",
    surface: "SYSTEM",
    parent: null,
    nav: "ENTRY",
    status: "IMPLEMENTED",
    session: "PUBLIC",
    capability: null,
    phase: null,
    restrictedAccount: false,
  },
  {
    id: "mobile.search",
    path: "/search",
    params: [],
    shell: "mobile.shared",
    surface: "SHARED",
    parent: null,
    nav: "STANDALONE",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: null,
    phase: null,
    restrictedAccount: false,
  },
  {
    id: "mobile.sessions._session-id",
    path: "/sessions/:sessionId",
    params: ["sessionId"],
    shell: "mobile.fighter",
    surface: "FIGHTER",
    parent: null,
    nav: "STANDALONE",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: "FIGHTER",
    phase: "ACTIVE",
    restrictedAccount: false,
  },
  {
    id: "mobile.sessions._session-id.complete",
    path: "/sessions/:sessionId/complete",
    params: ["sessionId"],
    shell: "mobile.fighter",
    surface: "FIGHTER",
    parent: "mobile.sessions._session-id",
    nav: "STACK",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: "FIGHTER",
    phase: "ACTIVE",
    restrictedAccount: false,
  },
  {
    id: "mobile.sessions._session-id.live",
    path: "/sessions/:sessionId/live",
    params: ["sessionId"],
    shell: "mobile.fighter",
    surface: "FIGHTER",
    parent: "mobile.sessions._session-id",
    nav: "STACK",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: "FIGHTER",
    phase: "ACTIVE",
    restrictedAccount: false,
  },
  {
    id: "mobile.settings",
    path: "/settings",
    params: [],
    shell: "mobile.shared",
    surface: "SHARED",
    parent: null,
    nav: "STANDALONE",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: null,
    phase: null,
    restrictedAccount: false,
  },
  {
    id: "mobile.settings.account",
    path: "/settings/account",
    params: [],
    shell: "mobile.shared",
    surface: "SHARED",
    parent: "mobile.settings",
    nav: "STACK",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: null,
    phase: null,
    restrictedAccount: false,
  },
  {
    id: "mobile.settings.apps",
    path: "/settings/apps",
    params: [],
    shell: "mobile.shared",
    surface: "SHARED",
    parent: "mobile.settings",
    nav: "STACK",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: null,
    phase: null,
    restrictedAccount: false,
  },
  {
    id: "mobile.settings.billing",
    path: "/settings/billing",
    params: [],
    shell: "mobile.shared",
    surface: "SHARED",
    parent: "mobile.settings",
    nav: "STACK",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: null,
    phase: null,
    restrictedAccount: false,
  },
  {
    id: "mobile.settings.blocked",
    path: "/settings/blocked",
    params: [],
    shell: "mobile.shared",
    surface: "SHARED",
    parent: "mobile.settings",
    nav: "STACK",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: null,
    phase: null,
    restrictedAccount: false,
  },
  {
    id: "mobile.settings.coach",
    path: "/settings/coach",
    params: [],
    shell: "mobile.shared",
    surface: "COACH",
    parent: "mobile.settings",
    nav: "STACK",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: "COACH",
    phase: "ACTIVE",
    restrictedAccount: false,
  },
  {
    id: "mobile.settings.data",
    path: "/settings/data",
    params: [],
    shell: "mobile.shared",
    surface: "SHARED",
    parent: "mobile.settings",
    nav: "STACK",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: null,
    phase: null,
    restrictedAccount: false,
  },
  {
    id: "mobile.settings.delete",
    path: "/settings/delete",
    params: [],
    shell: "mobile.shared",
    surface: "SHARED",
    parent: "mobile.settings",
    nav: "STACK",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: null,
    phase: null,
    restrictedAccount: false,
  },
  {
    id: "mobile.settings.delete.confirm",
    path: "/settings/delete/confirm",
    params: [],
    shell: "mobile.shared",
    surface: "SHARED",
    parent: "mobile.settings.delete",
    nav: "STACK",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: null,
    phase: null,
    restrictedAccount: false,
  },
  {
    id: "mobile.settings.help",
    path: "/settings/help",
    params: [],
    shell: "mobile.shared",
    surface: "SHARED",
    parent: "mobile.settings",
    nav: "STACK",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: null,
    phase: null,
    restrictedAccount: false,
  },
  {
    id: "mobile.settings.notifications",
    path: "/settings/notifications",
    params: [],
    shell: "mobile.shared",
    surface: "SHARED",
    parent: "mobile.settings",
    nav: "STACK",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: null,
    phase: null,
    restrictedAccount: false,
  },
  {
    id: "mobile.settings.privacy",
    path: "/settings/privacy",
    params: [],
    shell: "mobile.shared",
    surface: "SHARED",
    parent: "mobile.settings",
    nav: "STACK",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: null,
    phase: null,
    restrictedAccount: false,
  },
  {
    id: "mobile.settings.profile",
    path: "/settings/profile",
    params: [],
    shell: "mobile.shared",
    surface: "SHARED",
    parent: "mobile.settings",
    nav: "STACK",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: null,
    phase: null,
    restrictedAccount: false,
  },
  {
    id: "mobile.settings.security",
    path: "/settings/security",
    params: [],
    shell: "mobile.shared",
    surface: "SHARED",
    parent: "mobile.settings",
    nav: "STACK",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: null,
    phase: null,
    restrictedAccount: false,
  },
  {
    id: "mobile.settings.training",
    path: "/settings/training",
    params: [],
    shell: "mobile.shared",
    surface: "SHARED",
    parent: "mobile.settings",
    nav: "STACK",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: null,
    phase: null,
    restrictedAccount: false,
  },
  {
    id: "mobile.shared-session._shared-session-id",
    path: "/shared-session/:sharedSessionId",
    params: ["sharedSessionId"],
    shell: "mobile.fighter",
    surface: "FIGHTER",
    parent: null,
    nav: "STANDALONE",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: "FIGHTER",
    phase: "ACTIVE",
    restrictedAccount: false,
  },
  {
    id: "mobile.shared-session.new",
    path: "/shared-session/new",
    params: [],
    shell: "mobile.fighter",
    surface: "FIGHTER",
    parent: null,
    nav: "STANDALONE",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: "FIGHTER",
    phase: "ACTIVE",
    restrictedAccount: false,
  },
  {
    id: "mobile.signup",
    path: "/signup",
    params: [],
    shell: "mobile.auth",
    surface: "AUTH",
    parent: null,
    nav: "STANDALONE",
    status: "IMPLEMENTED",
    session: "GUEST_ONLY",
    capability: null,
    phase: null,
    restrictedAccount: false,
  },
  {
    id: "mobile.signup.consent",
    path: "/signup/consent",
    params: [],
    shell: "mobile.auth",
    surface: "AUTH",
    parent: "mobile.signup",
    nav: "STANDALONE",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: null,
    phase: "ONBOARDING",
    restrictedAccount: false,
  },
  {
    id: "mobile.signup.verify",
    path: "/signup/verify",
    params: [],
    shell: "mobile.auth",
    surface: "AUTH",
    parent: "mobile.signup",
    nav: "STANDALONE",
    status: "IMPLEMENTED",
    session: "GUEST_ONLY",
    capability: null,
    phase: null,
    restrictedAccount: false,
  },
  {
    id: "mobile.sparring.find",
    path: "/sparring/find",
    params: [],
    shell: "mobile.fighter",
    surface: "FIGHTER",
    parent: null,
    nav: "STANDALONE",
    status: "DEFERRED",
    session: "AUTHENTICATED",
    capability: "FIGHTER",
    phase: "ACTIVE",
    restrictedAccount: false,
  },
  {
    id: "mobile.store.cart",
    path: "/store/cart",
    params: [],
    shell: "mobile.fighter",
    surface: "FIGHTER",
    parent: null,
    nav: "STANDALONE",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: "FIGHTER",
    phase: "ACTIVE",
    restrictedAccount: false,
  },
  {
    id: "mobile.store.orders",
    path: "/store/orders",
    params: [],
    shell: "mobile.fighter",
    surface: "FIGHTER",
    parent: null,
    nav: "STANDALONE",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: "FIGHTER",
    phase: "ACTIVE",
    restrictedAccount: false,
  },
  {
    id: "mobile.store.orders._order-id",
    path: "/store/orders/:orderId",
    params: ["orderId"],
    shell: "mobile.fighter",
    surface: "FIGHTER",
    parent: "mobile.store.orders",
    nav: "STACK",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: "FIGHTER",
    phase: "ACTIVE",
    restrictedAccount: false,
  },
  {
    id: "mobile.store.product._product-id",
    path: "/store/product/:productId",
    params: ["productId"],
    shell: "mobile.fighter",
    surface: "FIGHTER",
    parent: null,
    nav: "STANDALONE",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: "FIGHTER",
    phase: "ACTIVE",
    restrictedAccount: false,
  },
  {
    id: "mobile.timer",
    path: "/timer",
    params: [],
    shell: "mobile.fighter",
    surface: "FIGHTER",
    parent: null,
    nav: "STANDALONE",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: "FIGHTER",
    phase: "ACTIVE",
    restrictedAccount: false,
  },
  {
    id: "mobile.timer.run",
    path: "/timer/run",
    params: [],
    shell: "mobile.fighter",
    surface: "FIGHTER",
    parent: "mobile.timer",
    nav: "STACK",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: "FIGHTER",
    phase: "ACTIVE",
    restrictedAccount: false,
  },
  {
    id: "mobile.training",
    path: "/training",
    params: [],
    shell: "mobile.fighter",
    surface: "FIGHTER",
    parent: null,
    nav: "NAV_ITEM",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: "FIGHTER",
    phase: "ACTIVE",
    restrictedAccount: false,
  },
  {
    id: "mobile.training.share",
    path: "/training/share",
    params: [],
    shell: "mobile.fighter",
    surface: "FIGHTER",
    parent: "mobile.training",
    nav: "STACK",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: "FIGHTER",
    phase: "ACTIVE",
    restrictedAccount: false,
  },
  {
    id: "mobile.trial",
    path: "/trial",
    params: [],
    shell: "mobile.shared",
    surface: "SHARED",
    parent: null,
    nav: "STANDALONE",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: null,
    phase: null,
    restrictedAccount: false,
  },
  {
    id: "mobile.welcome",
    path: "/welcome",
    params: [],
    shell: "mobile.auth",
    surface: "AUTH",
    parent: null,
    nav: "STANDALONE",
    status: "IMPLEMENTED",
    session: "GUEST_ONLY",
    capability: null,
    phase: null,
    restrictedAccount: false,
  },
  {
    id: "mobile.welcome.tour",
    path: "/welcome/tour",
    params: [],
    shell: "mobile.onboarding",
    surface: "ONBOARDING",
    parent: "mobile.welcome",
    nav: "WIZARD",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: "FIGHTER",
    phase: "ACTIVE",
    restrictedAccount: false,
  },
  {
    id: "mobile.workspaces",
    path: "/workspaces",
    params: [],
    shell: "mobile.shared",
    surface: "SHARED",
    parent: null,
    nav: "STANDALONE",
    status: "IMPLEMENTED",
    session: "AUTHENTICATED",
    capability: null,
    phase: null,
    restrictedAccount: false,
  },
] as const;

export const mobileShells = [
  {
    id: "mobile.root",
    parent: null,
    navItems: [],
  },
  {
    id: "mobile.auth",
    parent: "mobile.root",
    navItems: [],
  },
  {
    id: "mobile.onboarding",
    parent: "mobile.root",
    navItems: [],
  },
  {
    id: "mobile.fighter",
    parent: "mobile.root",
    navItems: [
      {
        key: "home",
        route: "mobile.home",
      },
      {
        key: "training",
        route: "mobile.training",
      },
      {
        key: "board",
        route: "mobile.board",
      },
      {
        key: "community",
        route: "mobile.community",
      },
      {
        key: "profile",
        route: "mobile.profile",
      },
    ],
  },
  {
    id: "mobile.coach",
    parent: "mobile.root",
    navItems: [
      {
        key: "today",
        route: "mobile.coach.today",
      },
      {
        key: "fighters",
        route: "mobile.coach.fighters",
      },
      {
        key: "board",
        route: "mobile.coach.board",
      },
      {
        key: "requests",
        route: "mobile.coach.requests",
      },
      {
        key: "inbox",
        route: "mobile.messages",
      },
    ],
  },
  {
    id: "mobile.gym",
    parent: "mobile.root",
    navItems: [
      {
        key: "pulse",
        route: "mobile.gym.pulse",
      },
      {
        key: "classes",
        route: "mobile.gym.classes",
      },
      {
        key: "checkin",
        route: "mobile.gym.check-in",
      },
      {
        key: "members",
        route: "mobile.gym.members",
      },
      {
        key: "staff",
        route: "mobile.gym.staff.on-shift",
      },
    ],
  },
  {
    id: "mobile.shared",
    parent: "mobile.root",
    navItems: [],
  },
] as const;

export const mobileGuards = {
  signIn: "mobile.login",
  entry: "mobile.root",
  notFound: "mobile.not-found",
  accountOnboarding: ["mobile.signup.consent", "mobile.onboarding.role"],
  workspaceChooser: "mobile.workspaces",
  defaultDestinationFallback: "mobile.workspaces",
  restrictedAccount: {
    suspended: "mobile.account.suspended",
    pendingDeletion: "mobile.account.pending-deletion",
  },
  returnToParam: "returnTo",
  intentParam: "intent",
  entryDestinations: {
    account_registration: "mobile.signup.consent",
    role_selection: "mobile.onboarding.role",
    fighter_onboarding: "mobile.onboarding.fighter",
    fighter_home: "mobile.home",
    coach_onboarding: "mobile.onboarding.coach",
    gym_onboarding: "mobile.onboarding.gym",
    sponsor_application: null,
  },
} as const;

export const mobileCapabilities = {
  FIGHTER: {
    home: "mobile.home",
    onboarding: "mobile.onboarding.fighter",
  },
  COACH: {
    home: "mobile.coach.today",
    onboarding: "mobile.onboarding.coach",
  },
  GYM_WORKSPACE: {
    home: "mobile.gym.pulse",
    onboarding: "mobile.onboarding.staff.role",
  },
  SPONSOR_WORKSPACE: {
    home: null,
    onboarding: null,
  },
  ADMIN: {
    home: null,
    onboarding: null,
  },
} as const;
